repos:
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: master
  hooks:
      - id: yapf
        language_version: python3.6
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
      - id: flake8
        args:
          - --ignore=E501,W5
