language: python

dist: xenial
  
git:
  depth: 3

jobs:
  allow_failures:
    - python: "3.8-dev"
  include:
    - &test
      stage: Test
      python: "2.7"
      cache: pip
      before_install:
        - pip install -U setuptools
      install:
        - pip install -r requirements.txt
        - pip install -e .[dev]
      script:
        - py.test -v
    - <<: *test
      python: "3.4"
    - <<: *test
      python: "3.5"
    - <<: *test
      python: "3.5-dev"
    - <<: *test
      python: "3.6"
    - <<: *test
      python: "3.6-dev"
    - <<: *test
      python: "3.7"
    - <<: *test
      python: "3.7-dev"
    - <<: *test
      python: "3.8-dev"
    - <<: *test
      python: "3.8"
      
    - stage: Check Examples
      name: AML 
      python: "3.8"
      script:
        - cd ./examples/aml
        - pip install -r requirements.txt
    - name: Django
      python: "3.8"
      script:
        - cd ./examples/yoti_example_django
        - pip install -r requirements.txt
    - name: Flask
      python: "3.8"
      script:
        - cd ./examples/yoti_example_flask
        - pip install -r requirements.txt
    - name: Doc Scan
      python: "3.8"
      script:
        - cd ./examples/doc_scan
        - pip install -r requirements.txt

    - stage: Analyze
      name: Sonarcloud
      python: "3.8"
      addons:
        sonarcloud:
          organization: "getyoti"
      install:
        - pip install -r requirements.txt
        - pip install -e .[dev]
      script:
        - pytest --cov=yoti_python_sdk yoti_python_sdk/tests --cov-report=xml:coverage-reports/coverage-new.xml
        - sed -i 's+<source>.*</source>+<source>/home/travis/build/getyoti/yoti-python-sdk/yoti_python_sdk</source>+g' coverage-reports/coverage-new.xml
        - sonar-scanner
      if: type = pull_request OR branch = master
