language: python

dist: xenial
  
# Only clone the most recent commit.
git:
  depth: 1

jobs:
  allow_failures:
    - python: "3.8-dev"
  include:
    - &test
      stage: Test
      python: "2.7"
      cache: pip
      before_install:
        - pip install -U setuptools
      install:
        - pip install -r requirements.txt
        - pip install -e .[dev]
      script:
        - py.test -v
    - <<: *test
      python: "3.4"
    - <<: *test
      python: "3.5"
    - <<: *test
      python: "3.5-dev"
    - <<: *test
      python: "3.6"
    - <<: *test
      python: "3.6-dev"
    - <<: *test
      python: "3.7"
    - <<: *test
      python: "3.7-dev"
    - <<: *test
      python: "3.8-dev"
    - <<: *test
      python: "3.8"
    - <<: *test
      stage: Coverage
      name: Coveralls
      python: "3.7"
      install:
        - pip install -r requirements.txt
        - pip install -e .[dev]
      script:
        - pytest --cov=yoti_python_sdk yoti_python_sdk/tests
      if: type = pull_request OR branch = master
      after_success:
        - coveralls
    - stage: Analyze
      name: Sonarcloud
      dist: trusty
      python: "3.6.1"
      addons:
        sonarcloud:
          organization: "getyoti"
      install:
        - pip install -r requirements.txt
        - pip install -e .[dev]
      script:
        - pytest --cov=yoti_python_sdk yoti_python_sdk/tests
        - sonar-scanner
      if: type = pull_request OR branch = master
