version: '3.4'
services:
  web:
    build:
      context: ./
      args:
        YOTI_APPLICATION_ID: "${YOTI_APPLICATION_ID}"
        YOTI_CLIENT_SDK_ID: "${YOTI_CLIENT_SDK_ID}"
        YOTI_FULL_KEY_FILE_PATH: "${YOTI_KEY_FILE_PATH}"
    ports:
     - "5000:5000"
   
    restart: always